//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GA.Board.Report.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class googleResults
    {
        public int ID { get; set; }
        public int websiteID { get; set; }
        public int metricID { get; set; }
        public int periodID { get; set; }
        public string value { get; set; }
    
        public virtual googleFinancialPeriods googleFinancialPeriods { get; set; }
        public virtual googleMetrics googleMetrics { get; set; }
        public virtual googleWebsites googleWebsites { get; set; }
    }
}
