//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GA.Board.Report.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class googleFinancialPeriods
    {
        public googleFinancialPeriods()
        {
            this.googleResults = new HashSet<googleResults>();
        }
    
        public int ID { get; set; }
        public int period_Number { get; set; }
        public System.DateTime start_Date { get; set; }
        public System.DateTime end_Date { get; set; }
        public int days { get; set; }
        public bool completed { get; set; }
    
        public virtual ICollection<googleResults> googleResults { get; set; }
    }
}
