//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GA.Board.Report.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class googleWebsites
    {
        public googleWebsites()
        {
            this.googleResults = new HashSet<googleResults>();
        }
    
        public int ID { get; set; }
        public int google_AccountID { get; set; }
        public string google_AccountName { get; set; }
        public int google_ProfileID { get; set; }
        public string google_ViewName { get; set; }
        public string website_Url { get; set; }
        public string twitter_Url { get; set; }
        public string twitter_ScreenName { get; set; }
        public string facebook_Url { get; set; }
        public string facebook_ScreenName { get; set; }
    
        public virtual ICollection<googleResults> googleResults { get; set; }
    }
}
