//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GA.Board.Report.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class googleMetrics
    {
        public googleMetrics()
        {
            this.googleResults = new HashSet<googleResults>();
        }
    
        public int ID { get; set; }
        public string metric_Name { get; set; }
        public string metric_Source { get; set; }
        public string metric_Value_One { get; set; }
        public string metric_Value_Two { get; set; }
        public string metric_Formula { get; set; }
        public string metric_GoogleQuery { get; set; }
    
        public virtual ICollection<googleResults> googleResults { get; set; }
    }
}
